// Builds data.js from Project Diablo 2's excel tables (data/global/excel inside the launcher's data.zip).
// Usage: node tools/build-data.js <dir with Weapons.txt, Armor.txt, ItemTypes.txt, Levels.txt, TreasureClassEx.txt, MonStats.txt> > data.js
const fs = require('fs');
const path = require('path');
const dir = process.argv[2] || '.';

function load(name) {
  const file = fs.readdirSync(dir).find(f => f.toLowerCase() === name.toLowerCase() + '.txt');
  if (!file) throw new Error(`${name}.txt not found in ${dir}`);
  const lines = fs.readFileSync(path.join(dir, file), 'latin1').split(/\r?\n/).filter(Boolean);
  const head = lines[0].split('\t');
  return lines.slice(1).map(l => {
    const cells = l.split('\t'), row = {};
    head.forEach((h, i) => { if (h && !(h in row)) row[h] = cells[i] ?? ''; });
    return row;
  });
}
const num = v => parseInt(v, 10) || 0;

const W = load('Weapons'), A = load('Armor'), IT = load('ItemTypes'), LV = load('Levels'), TC = load('TreasureClassEx'), MS = load('MonStats');
const itemTypes = Object.fromEntries(IT.filter(t => t.Code).map(t => [t.Code, t]));

// D2Common socket cap: min(gemsockets, the item's own ItemTypes MaxSock1/25/40 by ilvl <=25 / <=40 / >40)
const sockCaps = code => { const t = itemTypes[code]; return t ? [num(t.MaxSock1), num(t.MaxSock25), num(t.MaxSock40)] : [0, 0, 0]; };
// Class restriction comes from the type's own Class column (Equiv chains would wrongly mark daggers as Assassin-only)
const typeClass = code => (itemTypes[code] && itemTypes[code].Class) || '';

const types = {};
const items = [];
for (const it of [...W, ...A]) {
  if (it.spawnable !== '1' || !num(it.level) || !it.name || !it.code) continue;
  const tier = it.code === it.ultracode ? 3 : it.code === it.ubercode ? 2 : 1;
  if (!types[it.type]) types[it.type] = { n: itemTypes[it.type] ? itemTypes[it.type].ItemType : it.type, s: sockCaps(it.type), c: typeClass(it.type) };
  items.push({ n: it.name, c: it.code, t: it.type, tier, q: num(it.level), rl: num(it.levelreq), str: num(it.reqstr), dex: num(it.reqdex), gs: num(it.gemsockets) });
}
items.sort((a, b) => a.q - b.q || a.n.localeCompare(b.n));

// Highest weapN/armoN bucket reachable through TC upgrades at each monster level
const tcByName = Object.fromEntries(TC.filter(t => t['Treasure Class']).map(t => [t['Treasure Class'], t]));
function reach(name, seen = new Set()) {
  const t = tcByName[name]; if (!t || seen.has(name)) return 0;
  seen.add(name);
  let best = 0;
  for (let i = 1; i <= 10; i++) {
    const x = t['Item' + i]; if (!x) continue;
    const m = /^(?:weap|armo)(\d+)$/.exec(x);
    best = Math.max(best, m ? +m[1] : reach(x, seen));
  }
  return best;
}
const equip = TC.filter(t => /^Act \d( \([NH]\))? Equip [ABC]$/.test(t['Treasure Class']))
  .map(t => ({ n: t['Treasure Class'], l: num(t.level) })).sort((a, b) => a.l - b.l);
const tcReach = [0];
for (let m = 1; m <= 110; m++) {
  let top = equip[0];
  for (const e of equip) if (e.l <= m) top = e;
  tcReach.push(reach(top.n));
}

// Areas. Normal: regular monsters use their MonStats Level. Nightmare/Hell: Levels.txt MonLvl2Ex / MonLvl3Ex.
const monLevel = Object.fromEntries(MS.filter(m => m.Id).map(m => [m.Id, m]));
const SKIP = new Set([125, 126, 127, 132, 133, 134, 135, 136]); // Uber Tristram/Hell portals, boss-only, Pandemonium
const areas = [];
const seenKey = new Set();
for (const l of LV) {
  const id = num(l.Id);
  if (!id || id > 136 || SKIP.has(id) || !l.LevelName) continue; // ids after 136 are PD2 endgame maps
  const name = l.LevelName.trim().replace('Nihlathaks', "Nihlathak's");
  const act = num(l.Act) + 1;
  const regular = [];
  for (let i = 1; i <= 10; i++) {
    const m = monLevel[l['mon' + i]];
    if (m && m.boss !== '1' && num(m.Level)) regular.push(num(m.Level));
  }
  const lvls = [
    regular.length ? [Math.min(...regular), Math.max(...regular)] : [num(l.MonLvl1Ex), num(l.MonLvl1Ex)],
    [num(l.MonLvl2Ex), num(l.MonLvl2Ex)],
    [num(l.MonLvl3Ex), num(l.MonLvl3Ex)],
  ];
  lvls.forEach(([lo, hi], d) => {
    if (!hi) return;
    const key = `${d}|${act}|${name}|${lo}|${hi}`;
    if (seenKey.has(key)) return; // e.g. the seven Tal Rasha's Tomb rows
    seenKey.add(key);
    areas.push({ n: name, a: act, d, lo, l: hi, id });
  });
}

process.stdout.write('// Generated by tools/build-data.js from Project Diablo 2 excel tables. Do not edit by hand.\n');
process.stdout.write('window.D2DATA = ' + JSON.stringify({ items, types, areas, tcReach }) + ';\n');
